#Properties Config file
#Tue Jul 26 18:19:02 MSK 2022
server-name=SufixPvP
motd=SufixPvP
server-port=19132
online-mode=off
level-name=lobby
level-type=DEFAULT
gamemode=0
max-players=75
spawn-protection=-1
announce-player-achievements=off
white-list=off
enable-query=on
enable-rcon=on
rcon.password=DI5seqhlWl
spawn-animals=off
spawn-mobs=off
force-gamemode=off
hardcore=off
pvp=on
difficulty=1
generator-settings=
level-seed=
auto-save=on
view-distance=8
