#Properties Config file
#Mon Aug 15 21:11:47 MSK 2022
motd=SufixPvP Alpha
server-name=SufixPvP Alpha
server-port=19132
online-mode=off
gamemode=0
max-players=100
spawn-protection=-1
white-list=on
enable-query=on
enable-rcon=on
rcon.password=2cUdLe52jp
allow-flight=off
spawn-animals=on
spawn-mobs=on
force-gamemode=off
hardcore=off
pvp=on
difficulty=1
generator-settings=
level-name=lobby
level-seed=
level-type=DEFAULT
auto-save=on
view-distance=8
